### ISSUE TITLE
[documentation] Broken link to local install docs

### ISSUE THREAD

**Issue by peytondmurray** [Quansight/qhub#1004]
Currently the [local install documentation](https://docs.qhub.dev/en/stable/source/development/testing.md#local-testing) link is broken, creating a barrier to testing and adoption for new users. I didn't want to apply a **high priority** tag on this issue without first asking the community whether it really is high priority - but I definitely think it is. 

I remember accessing this link at some point in the past, and it contained information on how to set up minikube and MetalLB and so on. If someone else knows how to fix this quickly, I'd suggest that they take care of it - otherwise I can spend time whenever I find a chance to dig into how the docs find their way onto the website.

**Comment by iameskild** [comment]
Hey @peytondmurray, we have been updating the docs quite a bit recently and things may have been moved around. One or both of these might be what you're looking for:
- https://docs.qhub.dev/en/stable/source/dev_guide/minikube.html
- https://docs.qhub.dev/en/stable/source/dev_guide/testing.html

Those are up to date as of early Dec I believe, checkout `.../latest/source/...` for the updates we've made since then. I hope that helps.

**Comment by iameskild** [comment]
And if you have any suggestions on how to improve the docs, we'd be happy to hear them :)

**Comment by magsol** [comment]
@peytondmurray If you recall, can you provide the page that had the broken link? The main links on the top-level pages seem to be working correctly but I remember encountering this same issue a few months ago.

**Comment by peytondmurray** [comment]
@magsol Sure, it's here under the "Local Deployment of Existing Kubernetes Cluster" section: https://docs.qhub.dev/en/stable/source/installation/setup.html. Thanks for the help!

**Comment by iameskild** [comment]
Closing issue.
