### ISSUE TITLE
[BUG] - Azure import not correctly importing all resources

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1105]
### OS system and architecture in which you are running QHub

Linux (will occur on any OS)

### Expected behavior

Destroy should complete fully. Here are the important logs:

The error occurs here: https://github.com/Quansight/qhub-integration-test/runs/5297833224?check_suite_focus=true#step:7:18159

But the true error is occurring earlier due to import not capturing that several of the terraform-state resources that were previously created.

Error is here with resources not found https://github.com/Quansight/qhub-integration-test/runs/5297833224?check_suite_focus=true#step:7:283

### Actual behavior

Two of the three azure imports fail.

### How to Reproduce the problem?

Run the qhub-integration tests on azure.

### Compute environment

Azure

**Comment by viniciusdc** [comment]
This issue seems to be related to a mismatch betwen the [resources names](https://github.com/Quansight/qhub/blob/main/qhub/stages/input_vars.py#L30) during creation and import, they are difering only by the post hash string... which leads to resource not found.

I am still debuggin this, but #1109 might have fixed this by accident.

**Comment by viniciusdc** [comment]
This is now fixed after the mentioned PR
