### ISSUE TITLE
[ENH] - Simplify Docker images

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1145]
### Feature description

Right now there is a lot of configuration login embedded within our Docker images. This has many downsides with really the only upside I can see at the moment is it has reduced the complexity of our qhub pod image deployments. 
 - The qhub version is tightly coupled with the docker image version
 - End users have a harder time to add their own custom images
 - harder for qhub to make custom modifications

### Value and/or benefit

Easier development and allowing end users to use their own custom docker images

**Comment by costrouc** [comment]
Closed by #1174

**Comment by tonyfast** [comment]
currently there is jupyter specific information cooked into the docker images. this means that adding/removing features requires a new docker image and is costlier than it needs to be to create.

it could be practical to place the entire `qhub-jlab` environment in a meta-package/package that carries our `jupyter` opinions. with a separate package, extensions and tools can be added and tested outside of qhub. the changes then can propogate to qhub by referring the `qhub-jlab` rather than `qhub` managing the UX entropy.

**Comment by costrouc** [comment]
> currently there is jupyter specific information cooked into the docker images.

@tonyfast this is no longer true as of about 1 month ago. https://github.com/Quansight/qhub/blob/main/qhub/template/image/Dockerfile.jupyterlab. 

The docker images for everything are all just a collection of installed packages via apt/conda now. But I do agree that it needs to be documented explained how users can create their own images.
