### ISSUE TITLE
[BUG] - Qhub version shows 0.0.0 instead of 0.4.0

### ISSUE THREAD

**Issue by Adam-D-Lewis** [Quansight/qhub#1172]
### OS system and architecture in which you are running QHub

NixOS

### Expected behavior

I downloaded qhub 0.4.0 from conda-forge.  After running `from qhub.version import __version__; print(__version__)`, I'm seeing the version is `0.0.0`.  This has led to issues deploying qhub.  Running `python -m qhub init local --project=thisisatest  --domain github-actions.qhub.dev --auth-provider=password --terraform-state=local` has led to a qhub-config.yaml with image tags like `quansight/qhub-jupyterhub:v0.0.0` etc.  These images don't exist and qhub fails to deploy.  Changing the image tags to `v0.4.0` manually, but leaving qhub_version as `0.0.0` allowed me to deploy succesfully.

### Actual behavior

N/A

### How to Reproduce the problem?

N/A

### Command output

```bash session
N/A
```

### Versions and dependencies used.

N/A

### Compute environment

minikube

### Anything else?

N/A

**Comment by viniciusdc** [comment]
Hi @Adam-D-Lewis thanks for opening this issue, I didn't notice the cli version during testing. I will add a check to conda-forge qhub feedstock to fail if the version mismatches in the future. Now about the issue, the problem was due to the recent changes with the versioning Qhub uses, aka setuptools_scm, conda does not pick that dependency automatically when creating the build env for the package, so it was missing add 'setuptools_scm' to hosts during the build. I will fix that in the recipe and submit a new build for this version.

**Comment by viniciusdc** [comment]
Fixed with https://github.com/conda-forge/qhub-feedstock/pull/28, will take some hours until the next build is available on conda-forge

**Comment by viniciusdc** [comment]
The latest build is now available for download, @Adam-D-Lewis @iameskild I will close this issue as it was fixed.
