### ISSUE TITLE
[ENH] - Moving docker images to separate repository

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1174]
### Feature description

Would like to move the docker images to a separate repository so that we can encourage QHub to being more independent from what is in the image. E.g. encouraging that configuration is set via Kubernetes and packages are installed with the docker image. The dockerfile should be short and understandable.

I've already investigated binder/repo2docker. A few of the downsides I see:
  - repo2docker has a strong assumption that images have jupyter installed within them (dask-worker and jupyterhub) do not
  - repo2docker images sizes are huge see https://github.com/costrouc/repotest and https://hub.docker.com/repository/registry-1.docker.io/costrouc/repotest/ this results in a 500mb compressed image. Normally I would expect 100-200mb compressed for just those dependencies.

That said I do like the idea of repo2docker to have a directory with environment.yaml, apt.txt, postBuild, and start (entrypoint script) and we already have all but `start` in place already.

### Value and/or benefit

Encourage QHub to being more independent from what is in the image. Also significantly shortens the build time for QHub tests.

### Anything else?

Related issues:
- #1145 
- #715 
- https://github.com/Quansight/qhub/issues/785

**Comment by danlester** [comment]
I think this makes some sense for the jupyterlab images (so they can be developed separately), but as it stands not for jupyterhub and maybe others.

From our experience bringing terraform modules into the main repo, we found this sped up development considerably and avoided confusion. This worked because terraform would take the 'current' code each time automatically.

As it stands, jupyterhub image and terraform/Python code _are_ tightly-coupled, and the problem is more about how do we get kubernetes to mirror our repo's image code. This is a known problem and I believe there are better solutions - see e.g. [Tilt](https://tilt.dev/).

We could restructure things so that (perhaps) jupyterhub_config moves inside the image code so we have clearer boundaries. But I believe we would be making APIs for the sake of solving the wrong problem here.

It's more about build chains and dev environments. Things work fine in prod...

**Comment by costrouc** [comment]
Closes #1145

**Comment by iameskild** [comment]
As part of this move, I would like to also propose we try and tackle the enhancement @leej3 proposed in #715. If we can find a way to mount the conda-store PV to user's JupyterLab pod (happening already), the `hub` pod and any `dask-worker` pods, then I believe we might be able to further reduce the size and complexity of these images. 

If this is possible, then we can provide a set of "base images" which end-users can build on top of, perhaps using the `repo2docker` pattern that Chris mentioned above, or multi-stage builds.

**Comment by iameskild** [comment]
https://github.com/nebari-dev/nebari-docker-images/pull/1
