### ISSUE TITLE
[BUG] - GCP GPU support

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#1209]
### OS system and architecture in which you are running QHub

Linux (will occur on any OS)

### Expected behavior

GPUs working on gcp.

The fix:
 - https://github.com/Quansight/qhub/blob/main/qhub/template/stages/02-infrastructure/gcp/modules/kubernetes/nvidia_installer.tf uncomment and set the correct count calcualtions
 - https://github.com/Quansight/qhub/blob/main/qhub/stages/input_vars.py#L57-L64 fix the accelerator names

Additionally jupyterhub should be updated to version 2.2+ we are currently using 1.5 https://github.com/Quansight/qhub/blob/main/qhub/template/image/jupyterhub/environment.yaml#L6.

Closes https://github.com/Quansight/qhub/issues/1201
Closes https://github.com/Quansight/qhub/issues/1200

### Actual behavior

They do not work with the 0.4 release.

### How to Reproduce the problem?

Deploy QHub.

**Comment by viniciusdc** [comment]
Ok, An update to this issue:

- I added the first modifications related to re-enabling the GPU support for GCP (ref. https://github.com/Quansight/qhub/compare/fix-1209-gpu)
- Then, when testing a deployment I found the following error:
```
[terraform]: │ Error: Failed to create daemonset: Post "http://localhost/apis/apps/v1/namespaces/kube-system/daemonsets": dial tcp [::1]:80: connect: connection refused
[terraform]: │ 
[terraform]: │   with module.kubernetes.kubernetes_daemonset.nvidia_installer[0],
[terraform]: │   on modules/kubernetes/nvidia_installer.tf line 1, in resource "kubernetes_daemonset" "nvidia_installer":
[terraform]: │    1: resource "kubernetes_daemonset" "nvidia_installer" {
```
I am still not totally sure about why its timing out, but inspecting the console logs might give some insights into where the error is originating from
```
E0329 19:50:44.747210   ...  Error: "MountVolume.SetUp failed for volume \"nvidia\" 
(UniqueName: \"kubernetes.io/host-path/9f5d8b6b-e3d5-42a1-ab4b-81785c5e7e07-nvidia\")
pod \"nvidia-gpu-device-plugin-pwmmt\" (UID: \"...") : hostPath type check failed: 
/home/kubernetes/bin/nvidia is not a directory
```

**Comment by viniciusdc** [comment]
@costrouc I tested the version bump for Jupyterhub, no problems so far. Seems that we will be able to move forward with that change.

**Comment by viniciusdc** [comment]
So, I am trying to get some simple code snippets for GPU workloads, just to guarantee the user will be able to use the GPU within Qhub. I also tested the Jupyterhub 2.2.2 version update, no issues so far I validate that the above problem with Nvidia taint was fixed with it (Will open a separate PR later)

**Comment by tylerpotts** [comment]
@viniciusdc @costrouc Worth noting that this same error is happening with AWS. 

We may need to reconsider how this is implemented. Currently stage 03 is cloud agnostic, and the nvidia daemonset is cloud-specific. The current error arises because kubernetes hasn't been initialized yet which happens in stage 03.

Perhaps we could move the k8s initialization to stage 03? That might be annoying because the same code will be duplicated 4x in terraform across the various cloud specific folders. 

Another option may be to add another stage specifically for GPU between stage 3 and 4

**Comment by magsol** [comment]
> So, I am trying to get some simple code snippets for GPU workloads, just to guarantee the user will be able to use the GPU within Qhub. I also tested the Jupyterhub 2.2.2 version update, no issues so far I validate that the above problem with Nvidia taint was fixed with it (Will open a separate PR later)

If we can do this without the JHub 2.2.2 upgrade, we can roll this into 0.4.1.

**Comment by tylerpotts** [comment]
@magsol Just wanted to make sure you all are aware of this comment above: https://github.com/Quansight/qhub/issues/1209#issuecomment-1106863532

Currently this PR will break AWS GPU support

**Comment by viniciusdc** [comment]
> @magsol Just wanted to make sure you all are aware of this comment above: [#1209 (comment)](https://github.com/Quansight/qhub/issues/1209#issuecomment-1106863532)
> 
> Currently this PR will break AWS GPU support

Hi, @tylerpotts definitely, I updated the original PR to move GCP and AWS daemonsets to a cloud-based module in the 03-stage. That will fix the issue for now, but I do agree that having a target stage for this would be better,
