### ISSUE TITLE
Server prompts for restart

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#131]
Qhub is currently experiencing the bug described here:

https://github.com/jupyterlab/jupyterlab/issues/7081

**Comment by tylerpotts** [comment]
@brl0 Are you still experiencing this problem? How frequently?

**Comment by brl0** [comment]
@tylerpotts,
It hasn't happened recently, but that could be because we haven't been running heavy loads lately.
I suspect the problem is due to the ingress controller being overloaded because when I observed the issue in the past the cpu usage for that pod was very high (according to k9s).
To help with this issue on our qhub instance, I increased the size of the general node group instance type to `n1-standard-4`.
I also think it might be possible that the dask gateway upgrade may help alleviate the issue to some degree because it has its own traefik proxy.

**Comment by tylerpotts** [comment]
@brl0 Thanks for the update. I'm also hoping that with the release of `v0.3` (scheduled for Mar 29th) when we shift to traffik over nginx this might change things here as well

**Comment by rsignell-usgs** [comment]
@jkellndorfer and I are hitting this too on the ESIP AWS-deployed qhub (https://jupyter.qhub.esipfed.org):
![image (3)](https://user-images.githubusercontent.com/1872600/111613059-8038c800-87b4-11eb-9f37-cf6c7d47ce51.png)

We are eagerly awaiting the new release and hoping that switching from nginx to traefik will do the trick, but in the meantime, we are planning to follow your lead and increase our general node group instance type from `m5.large` (2vcpu, 4GB) to `m5.xlarge` (4vcpu, 16GB).   

Can we just make that change in the qhub config and expect things to go smoothly?

**Comment by brl0** [comment]
@iameskild and I are seeing this issue more frequently on our new qhub instance on AWS.
