### ISSUE TITLE
On-premise configuration documentation

### ISSUE THREAD

**Issue by lgonzalezsa** [Quansight/qhub#132]
Hello!
Wondering where I can find documentation or examples to deploy and configure qhub on-premise infrastructure.
Would like to test it in a personal server before cloud.
Thanks!

**Comment by tylerpotts** [comment]
Great question. There isn't currently documentation or ability to do this with the current state of QHub, but it is something that that has been discussed. The thought is to use minikube and have Terraform create a local cluster.

In the short term, you might consider spinning this up on Google Cloud since you get $300 in credits when you first sign up. The default configuration will run from ~$20-$100/month in compute costs depending on how many user nodes / dask workers you spin up. Running `terraform destroy` in the `infrastructure` and `state` folders once you're done testing would delete all the infrastructure.

**Comment by dharhas** [comment]
@lgonzalezsa Expanding on @tylerpotts comment.

On-Prem kubernetes is a pain and doesn't quite fit our target audience of folks who do not have strong in house devops. We have a sister project called qhub-hpc (that is not yet open sourced) that allows you to go from bare metal to an HPC setup with QHub integration. We are also experimenting with things like Nomad and k3s for an op-prem Kubernetes story. 

We are also working on a pr to make testing on-prem with minikube easier.

**Comment by laisbsc** [comment]
Hey @lgonzalezsa,

hope you're doing good! Thank you so much for reaching out to us.

I am sorry that we could not be more helpful. I will go ahead and close this for now, though. Feel free to reopen in case something else pops into your mind.

Take care.
