### ISSUE TITLE
[BUG] - `azurerm` v2.44.0 not supported on M1 Mac

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#1430]
### OS system and architecture in which you are running QHub

M1 Mac

### Expected behavior

Deploying Qhub on Azure from an M1 Mac should work.

### Actual behavior

When I try to deploy on Azure from my M1 Mac, I run into the following error:

```terraform
INFO:qhub.provider.terraform:terraform init directory=stages/01-terraform-state/azure
INFO:qhub.provider.terraform: terraform at /var/folders/sb/dqkqvyn15zgchvy93lsf0nbm0000gn/T/terraform/1.0.5/terraform
[terraform]: Upgrading modules...
[terraform]: - terraform-state in modules/terraform-state
[terraform]:
[terraform]: Initializing the backend...
[terraform]:
[terraform]: Initializing provider plugins...
[terraform]: - Finding hashicorp/azurerm versions matching "2.44.0"...
[terraform]: ╷
[terraform]: │ Error: Incompatible provider version
[terraform]: │
[terraform]: │ Provider registry.terraform.io/hashicorp/azurerm v2.44.0 does not have a
[terraform]: │ package available for your current platform, darwin_arm64.
[terraform]: │
[terraform]: │ Provider releases are separate from Terraform CLI releases, so not all
[terraform]: │ providers are available for all platforms. Other versions of this provider
[terraform]: │ may have different platforms supported.
[terraform]: ╵
[terraform]:
```

### How to Reproduce the problem?

Try deploy QHub (any recent version or from main) on an M1 Mac.

**Comment by iameskild** [comment]
Although I can find mention of M1 support on the [provider's repo](https://github.com/hashicorp/terraform-provider-azurerm), I believe the solution is simply upgrading to a new version of the `azurerm` provider: 
https://stackoverflow.com/questions/72633451/terraform-azurerm-provider-incompatible-for-mac-m1

**Comment by tjcrone** [comment]
I ran into this problem just this weekend and can confirm that 0.3.22 appears to work well on the M1 (https://github.com/tjcrone/qhub/commit/5d115f4b463ccb0f6770fe01956040d0b83d14ba). Of course there is no easy way to integrate this into my Qhub CI because even if I rewrite the action so that it pip installs directly from my repo, ```qhub deploy``` clobbers that on every update. I've resorted to dusting off an old Intel Mac to run Qhub with Azure.

cc: @rsignell-usgs

**Comment by tjcrone** [comment]
As I have worked on this for many hours this weekend, I have wondered if maybe I am doing this all wrong anyway. Is there a way to build a Qhub config file (and support files, e.g. stages, .github, etc.) and push to my GitHub repo so that I can do an initial deploy using GitHub Actions? Or is it required that I do an initial deploy from my local machine before I engage the services of the CI? From what I can tell, a fully functioning CI repo is not built until a local deploy is executed. However, based on my initial investigation over the weekend, I'm not seeing a reason why this needs to be the case. Having the initial deployment run inside of the workflow Docker image would obviate the pain of having to deal with asurerm on the M1. Does anyone have any feelings about this? Any suggestions? Is this impossible? Thanks!

**Comment by iameskild** [comment]
Hi @tjcrone, thank you for the feedback! I'm glad to hear that you were able to deploy an Azure cluster on an M1 mac. As a short-term workaround, you can add `--disable-render` to the deploy command and it will avoid overwriting the files you manually edited.

As for deploying QHub for the first time using GHA, I haven't tried this but I don't see a reason why this wouldn't work. I would assume that the `--dns-provider cloudflare --dns-auto-provision --disable-prompt` is setup so that we don't need to provide any input during the deployment. (Cloudflare is the only DNS provider that has `dns-auto-provision` setup).

**Comment by tjcrone** [comment]
Thanks for this input @iameskild. The reason I don't think it will work is that the .github workflows are not generated by `qhub init`, but rather only by `qhub deploy`. So a local deploy seems to be required, followed by the push (including the workflows) to GitHub, at which point the workflows will run. Am I missing something?

Along the same lines, I'm not sure why the GitHub OAuth information needs to be passed at the command line during init, rather than supplied with an env variable. Maybe it's possible and I didn't find this info in the docs. Other really helpful switches for the init with Azure is the region. Is this something that can be passed to init? Thanks!

**Comment by iameskild** [comment]
@tjcrone I forgot to mention that `qhub render` needs to be run prior to committing and pushing the code up to GH. Render is called during the deploy command and it is what generates all the files (`stages`. `.github`, etc). So I assume that once the `.github` folder is rendered, it should work but perhaps there is something else that I am missing. 

As for using github as the auth-provider, I think you bring up a good point. We are currently working on updating the CLI and this is great feedback :)

**Comment by tjcrone** [comment]
Oh fantastic! That is the step I was missing. I will try `qhub render` to see if I can do the initial deploy to Azure using GitHub Actions on the M1. Thanks!

**Comment by iameskild** [comment]
Hey @tjcrone, I'd like to encourage you to open a PR with you fix :)
