### ISSUE TITLE
qhub / ovh support

### ISSUE THREAD

**Issue by x0rzkov** [Quansight/qhub#189]
Hi,

Hope you are all well !

Is it possible to support OVH also for european countries ?

Thanks for any insights or inputs on that question.

Cheers,
X

**Comment by costrouc** [comment]
@x0rzkov it looks to me that OVH has an REST api for managing dns entries. We welcome PRs on this issue. In order to support OVH we would simply need a function implemented in `qhub.providers.dns.ovh:update_record` similar to https://github.com/Quansight/qhub/blob/master/qhub/provider/dns/cloudflare.py.
