### ISSUE TITLE
More jupyterlab extensions (nbgitpuller)

### ISSUE THREAD

**Issue by gmaze** [Quansight/qhub#231]
## Description

For a class I give, I'd like to be able to use [nbgitpuller](https://jupyterhub.github.io/nbgitpuller/link.html) with my qhub deployment on GCP.

To do so, I need to modify files under the jupyterlab folder:
- Add ``nbgitpuller`` to ``jupyterlab/labextensions.txt``
- Add pip install of ``nbgitpuller`` to ``jupyterlab/environment.yaml``

## Suggestion
Would it be possible to implement in the ``config-hub.yml`` file a new section for more jupyterlab extensions ?

Alternatively, it may be faster to simply add the ``nbgitpuller`` extension to the default qhub set-up ? (I could send a PR for this)

**Comment by costrouc** [comment]
> Would it be possible to implement in the config-hub.yml file a new section for more jupyterlab extensions ?

Due to jupyterlab3 being released I would prefer not to add a specific section for extensions. Extensions should not longer require a build step when being installed. 

> Add pip install of nbgitpuller to jupyterlab/environment.yaml

You can use a custom docker image for jupyterlab in `qhub-config.yaml` it is configurable and detailed in https://qhub.dev/docs/do/configuration.html#default-images. Make sure to base the docker image on https://github.com/Quansight/qhub/tree/master/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/image.

Does this answer the question you have? I do agree that we need an easier way to customize docker images for qhub but I think that jupyterlab 3 will solve many of these issues.

**Comment by gmaze** [comment]
thanks @costrouc for your quick answer ! 

> You can use a custom docker image for jupyterlab in `qhub-config.yaml`
Do you think this is a faster solution than to fork qhub and to modify source ?
I guess yes...

> Does this answer the question you have?
yes ! I understand this is all still very new and evolving, and with Jupyter lab it will be easie

any idea when qhub will move to 3.0 ?

**Comment by tylerpotts** [comment]
@gmaze We haven't had a conversation about 3.0 yet. I'll put it on our agenda to discuss internally and get back to you

**Comment by dharhas** [comment]
@tylerpotts if we don't already have one, go ahead and make a jlab 3.0 issue.

**Comment by laisbsc** [comment]
Hey @gmaze! So good to see you around here.

> Do you think this is a faster solution than to fork QHub and to modify the source?
> I guess yes...

Jackpot! 💯 easier than modifying the source code. Also, this is not as urgent on our roadmap since 3.0 was just launched. We're happy to change our plans to fit the community's needs, though.
 
> any idea when QHub will move to 3.0?

We had a discussion about it last week (Thanks for bringing it up, by the way) and the team decided that although important, it is best to wait and see how the community adopts version 3.0. For now, we are focusing on tests and stability. Some cool stuff coming around.

Finally, if the use of Jupyter 3.0 is essential for you, I hope you've managed to implement [Chris' suggestions](https://github.com/Quansight/qhub/issues/231#issuecomment-756164370).

I will go ahead and close this issue now but please let us know if there's anything else we can do for you. And feel free to reopen it in case you have any further questions.
