### ISSUE TITLE
Enable a way to text chat with other folks logged in?

### ISSUE THREAD

**Issue by rsignell-usgs** [Quansight/qhub#237]
## Description
As admin, when I see someone else logged in:
![2021-01-10_10-53-19](https://user-images.githubusercontent.com/1872600/104127871-8d5bb580-5332-11eb-9cd6-606faecc95ec.png)
perhaps I'd like to tell them to please join the Jitsi video chat I started. 
But how to do that?

## Suggestion
> What are your suggestions on how to solve this problem? What solution(s) would make you happy?

Would "talk" work from the terminal if installed? 
Any way to chat other qhub users would be cool

## Context
> How important is this feature for you? 

It's not that important.   Just would be nice.

**Comment by tylerpotts** [comment]
@rsignell-usgs That would be a nifty feature! I know @tonyfast has a lot of ideas in this area

**Comment by costrouc** [comment]
> Would "talk" work from the terminal if installed? Any way to chat other qhub users would be cool

I don't think this would work since each user is running in a seperate pod. 

Right now I think the easiest approach is to use the jitsi integration in qhub in the top right hand corner. 

![image](https://user-images.githubusercontent.com/1740337/104471688-2421af80-5589-11eb-9ded-57baf584cf7e.png)

Here is what happend when you join a room.

![image](https://user-images.githubusercontent.com/1740337/104471784-41ef1480-5589-11eb-82f2-e52cfec535b8.png)

**Comment by rsignell-usgs** [comment]
@costrouc , okay so I get why "talk" won't work.

But I don't understand how to contact someone to tell them you would like to have them join a meeting you have created.    Are you saying there is a way within Jitsi to ping someone?

**Comment by dharhas** [comment]
I don't think so. Jitsi has no idea who else is logged into jupyterhub.

**Comment by dhirschfeld** [comment]
Maybe a zulip interface could be embedded in a sidebar which simply connected to an existing zulip server
