### ISSUE TITLE
Support additional DNS providers

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#325]
I found a Terraform [example](https://www.hashicorp.com/blog/using-the-kubernetes-and-helm-providers-with-terraform-0-12) from Hashicorp of using [ExternalDNS](https://github.com/kubernetes-sigs/external-dns) to create DNS records for external services.  Here is a video [demonstration](https://youtu.be/zHc2dUBiye4) linked by the example article.

ExternalDNS supports CloudFlare, AWS, GCP, Azure, DO and many more.
A related issue #189 requests OVH support , which ExternalDNS also supports.  

This is a duplicate of issue #206, which was closed as out of scope.  I thought that this example might be more motivating than the previous issue.  However, if this issue is still considered out of scope, feel free to close.

**Comment by laisbsc** [comment]
Hey @brl0, thank you for all your contributions to QHub.

It is funny you suggest this now because I was about to ask about the use/implementation of additional DNS registers, besides Cloudflare for the docs.

Is this something you'd be willing to work on implementing? I have no idea how much work it will be but I think it would be quite a nice addition to QHub. We can add it to the tech-discussion meeting and see the next steps if you are.

**Comment by brl0** [comment]
Honestly, this is not something I am likely to work on anytime soon.  
I would however suggest keeping this issue open as I still think it is a worthwhile consideration for expanding DNS support.

**Comment by tylerpotts** [comment]
Moving this to icebox for now as it's not currently in our roadmap
