### ISSUE TITLE
User and Group management page for JupyterHub

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#367]
There needs to be a way to associate metadata with user/groups and edit those values:

Example user cases:
  - https://github.com/yuvipanda/jupyterhub-ssh we would like to associate ssh public/private keys with user
  - https://github.com/Quansight/qhub-cloud/blob/dev/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/templates/jupyterhub_config.py.j2#L27 we need to associate a uid/gid to groups etc. 

Would be nice to have api endpoints that expose:
  - public information about a user that is accessible to anyone
  - secrets that can be create/update/deleted I'm inspired by https://docs.github.com/en/rest/reference/actions#secrets

We can envision with secrets an admin / user of a group could add environment variables that then get set on the launched jupyterlab or dashboard.

**Comment by danlester** [comment]
**Jupyterhub_ssh simplest case:**

- jupyterhub_config.py needs to import a custom handler, which in turn imports a UserMetadata ORM model. This gives us an extra table in the JupyterHub database, and give it the same key as the User table.
- Add a UI handler for a new User Metadata page(s) so we can enter metadata attributes for any user, probably stored in JSON form in the DB, but with individual entries on different rows in the UI. e.g. enter 'jupyterhub_ssh_publickey' for a user.
- Add a handler for the REST API to get metadata for a named user

Note that in order to simplify the import process in JupyterHub, it would be easier not to have a direct ORM link between User and UserMetadata.

Assuming jupyterhub_ssh is able to call our API, this should be sufficient if e.g. we wanted to store a 'jupyterhub_ssh_enabled' flag as user metadata, and then change jupyterhub_ssh so that it checks this flag for a user before allowing access (via password token) or not.

However, for access via SSH private key, I'm not sure if the above is sufficient at scale - that the user identity won't be known unless jupyterhub_ssh can look up a user based on the public key stored in metadata value. i.e. it may need to map from public key to user, rather than just user to metadata value.

If this is the case, then it might be possible to run an extra REST endpoint to do that lookup, perhaps caching all metadata values in memory.

I haven't thought yet about adding encryption for secrets.

**For the uid look up case:**

I've perhaps misunderstood, but I'm not sure how this could work as JupyterHub UserMetadata - surely mapping from user to uid needs to happen well before JupyterHub even exists, at the qhub render stage?
