### ISSUE TITLE
source .bashrc required for every log in

### ISSUE THREAD

**Issue by kcpevey** [Quansight/qhub#499]
## Describe the bug
I have to `source .bashrc` every time I log in.

## How can we help?
Help us help you.
* What are you trying to achieve? To use .bashrc to set up my environment

I'm told a workaround is to put everything into `.profile`

## Your environment
QHub 0.3

**Comment by leej3** [comment]
There are two contexts that are relevant here, system calls from the notebook and the jupyter terminal app. There are a few settings for notebook server configuration that affect the notebook system calls but otherwise we don't seem to have too much control over that I can tell.

Regarding the terminal app setup I had similar issues. I confirm that .bashrc and .profile are not sourced. .bash_profile is sourced though. If you just add `source ~/.bashrc` to this file you should be good to go. It's worth noting .profile will only be sourced by bash if .bash_profile is missing.

I found this somewhat helpful in outlining the details of how the terminal app is set up:
https://github.com/jupyterlab/jupyterlab/issues/3094

There is still some stuff that I do not understand:
+ If .bash_profile is being sourced instead of .bashrc I would expect `echo $0` to return "-bash" rather than the actual output of "/bin/bash"
+ Having sourced my .bashrc I have vim on my PATH. I can use vim but `which vim` and `hash vim` show no vim available. Not a big deal right now but understanding this will help in debugging issues if they occur down the line.

**Comment by viniciusdc** [comment]
@aktech any thoughts on this, this seems to be solved already
