### ISSUE TITLE
[bug] QHub render on v0.3.6 doesn't create .github/workflows directory

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#546]
## Describe the bug
`.github/workflows` isn't being rendered when `qhub render -c qhub_config.yaml ./` is run. 

## Your environment
Qhub version `0.3.6`

**Comment by tylerpotts** [comment]
This also isn't being created with qhub init:

```
$ qhub init aws
Provide project name: test
Provide domain: test
Visit https://github.com/settings/developers and create oauth application
  set the homepage to: https://test/
  set the callback_url to: https://test/hub/oauth_callback
Github client_id: test
Github client_secret: st
$ ls -al
total 84
drwxrwxr-x 7 tyler tyler  4096 Apr 29 09:06 .
drwxr-xr-x 5 tyler tyler  4096 Apr 23 15:48 ..
drwxrwxr-x 2 tyler tyler  4096 Apr 29 08:53 environments
-rw-rw-r-- 1 tyler tyler   286 Apr 23 16:34 .envrc
drwxrwxr-x 8 tyler tyler  4096 Apr 29 08:53 .git
-rw-rw-r-- 1 tyler tyler   129 Apr 29 08:53 .gitignore
drwxrwxr-x 6 tyler tyler  4096 Apr 23 16:02 image
drwxrwxr-x 3 tyler tyler  4096 Apr 29 08:53 infrastructure
-rw-rw-r-- 1 tyler tyler 17600 Apr 23 15:49 old_qhub-config.yaml
-rw-rw-r-- 1 tyler tyler   379 Apr 23 16:45 pod.yaml
-rw-rw-r-- 1 tyler tyler  3657 Apr 29 09:06 qhub-config.yaml
drwxrwxr-x 3 tyler tyler  4096 Apr 29 08:53 terraform-state
-rw-rw-r-- 1 tyler tyler 18948 Apr 29 08:53 v2_qhub-config.yaml
$ qhub --version
0.3.6
```

**Comment by costrouc** [comment]
This was a breaking change from 0.2 -> 0.3. https://docs.qhub.dev/en/latest/source/02_get_started/04_configuration.html#continuous-integration-and-continuous-deployment. Since qhub now supports multiple ci providers the default is none. If you want a ci provider you can specify `--ci-provider=github-actions` for example.

If you have an existing `qhub-config.yaml` you need to add a `ci_cd` key detailed in the docs https://docs.qhub.dev/en/latest/source/02_get_started/04_configuration.html#continuous-integration-and-continuous-deployment.

**Comment by tylerpotts** [comment]
This is working as expected with the update from `v0.2.x` to `v0.3.x`. The ci_cd block needs to be defined in `qhub_config.yaml` like so:
```
ci_cd:
  type: github-actions
  branch: main
```
Relevent documentation: 
https://docs.qhub.dev/en/latest/source/02_get_started/04_configuration.html#continuous-integration-and-continuous-deployment
