### ISSUE TITLE
Ensure that kubespawner override `environment` is overriable

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#571]
I'd like to make it so that the user can specify the path and ld_library_path. Currently right now this is overwritten by https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/templates/jupyterhub_config.py.j2#L102-L109. The reason for this is that /usr/local/nvidia only works on gcp and when we try and support AWS we will run into this same problem. Here if we make that fix this will work https://github.com/Quansight/qhub-deployment-quansight/blob/main/qhub-config.yaml#L194-L196.

```python
profile['kubespawner_override']['environment'] = {
     'LD_PRELOAD': 'libnss_wrapper.so',
     'NSS_WRAPPER_PASSWD': '/tmp/passwd',
     'NSS_WRAPPER_GROUP': '/tmp/group',
     'NB_UMASK': '0002',
     'SHELL': '/bin/bash',
     'HOME': '/home/jovyan',
    **profile.get('kubespawner_override', {}).get('environment', {})
}
```

**Comment by aktech** [comment]
Pasting my comment from slack here before it gets lost.

>I was looking at options to initialise the GPU environment (for GCP) on QHub, the best option I see so far is via .bash_profile Also, I don't see a problem in putting Nvidia libs to the path to bash_profile irrespective of we have GPUs enabled or not (for GCP at the moment), otherwise we'll have to add a field in qhub-config.yml for explicitly doing that on top of the following, which is probably error prone.

4 things here:

- The bash_profile I suggested is not overwritten by the kubespawner environment as the .bash_profile is created on the post start hook (I have tested it as well)
- I think its not a good idea to let the user write the PATH and LD lib path on the config because the installation of drivers is done by QHub via nvidia installer daemon set and not by the user, so user should not worry about putting the path to lib and hardcoding the path like that in the config is error prone and can have side effects.
- This is cloud specific, that's why I suggest putting things in bash profile based on cloud provider
- The most we could do, may be later is giving the user ability to configure bash_profile via qhub config

How does that sounds?
