### ISSUE TITLE
Dask gateway cluster object and client not reporting same node count

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#598]
## Describe the bug

> We have noticed a few issues with communication between the dask gateway cluster and jupyterlab on the ESIP Qhub 0.3.1.   Both the GatewayCluster widget and the Dask Labextension in Jupyterlab seem to stop getting information from the cluster.  So for instance, the cluster widget and the client command showing different numbers of workers, and the dask dashboards widgets stop updating their info (while opening the same dask dashboard URL in a brower tab works fine).    Here's a screenshot:
Should I raise this as a github issue? @rsignell-usgs 

![image](https://user-images.githubusercontent.com/1740337/119142057-06bb9100-ba14-11eb-9308-c2a73eb0fe69.png)

**Comment by rsignell-usgs** [comment]
I am not using adaptive scaling.    @jkellndorfer had this same issue during his Pangeo Showcase talk -- it appears that Dask had stopped working (because the task stream stopped displaying activity), but in fact Dask was still working. Check out 15 seconds starting here: https://youtu.be/Xco9OhTXh2w?list=PLuQQBBQFfpgpF3eGnlgXNqWmXhND3Vzg_&t=1307

**Comment by tarundmsharma** [comment]
hi @costrouc Is this issue resolved?
