### ISSUE TITLE
Additional conda dependencies [documentation]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#614]
I think a visible section in the docs would be great for this. Aggregating the ways in which people may need to modify the conda environments would be very useful. It would serve as a menu for functioanality that people can choose from as they are determining what they want to add to their environments. It could be conceived as an index organized by use-case that links to all of the relevant sections in the docs.

To seed the discussion...

+ nb_conda_kernels needs to be in the environment that launches the jupyterlab instance
+ ipykernel needs to be in every environment you wish to access from the notebook interface (though you can still access them from the terminado based shell)
+ cudatoolkit needs to be added to any environment that will be using a GPU (along with a link to the existing GPU setup docs)
+ dask deps... link to existing docs and list dask, distributed, dask-gateway
+ authentication software? Not sure of this one but things like google auth etc... a little deployment specific rather than use case specific though.
+ cdsdashboards setup (single user in dashboard env and core package in the env from which jupyterlab is launched)
+ clients for extensions of the core deployment. I'm thinking like prefect, clearml etc.
+ debugpy for vscode based debugging
+ is their xorg libraries that could cover typical graphical usecases? And perhaps mesa for GLX driven X usage of GPUs... unlikely use case perhaps.

EDIT: cds dashboards also needs `notebook` or some other package to satisfy the nbformat interface of bokeh

**Comment by tylerpotts** [comment]
@leej3 Are you able to attend next weeks meeting on Tuesday at 8:30AM CST to discuss?

**Comment by leej3** [comment]
Sure. I have 30 mins then.

**Comment by tylerpotts** [comment]
@leej3 What are the next steps you hope to come out of this issue? I see a mixture of feature requests and discussion items above. Are there any that are higher priority than others?

My thought is that anything in particular that is actionable we should split out into a separate issue

**Comment by leej3** [comment]
Oh, I didn't mean to add feature requests. I was largely documenting all the gotchas I encountered when expanding our use of QHub.  I think a need for user docs(rather than docs for deployment) has been raised in a separate issue. I think I envisioned a section in those docs named "common dependencies" and have a number of use-cases defined in which the various dependencies are listed. I appreciated that part of this is just comfort with the jupyter/python data science stack... 

Perhaps @kcpevey could comment because she has used QHub for longer. Kim do you feel the addition of such docs would be within the realm of QHub docs or is this just standard env setup that one might expect on any infrastructure?

**Comment by brl0** [comment]
I also think this is a good idea.

Here are some other possible considerations just brainstorming while looking over our conda environment, although these are not as crucial as some of the others suggested:
- fsspec, gcsfs, s3fs, adlfs: cloud storage file system implementations
- [universal_pathlib](https://github.com/Quansight/universal_pathlib): great pathlib-like fsspec wrapper
- pyarrow, fastparquet: fast, cloud friendly file format support
- intake, intake-parquet, intake-xarray: used to access data catalogues
- pyviz_comms: may be needed if using holoviz tools
- aws-shell, gsutil, etc: cloud specific command line tools
- cython, numba, [numba::icc_rt](https://numba.pydata.org/numba-doc/latest/user/performance-tips.html#intel-svml): [performance enhancing](https://pandas.pydata.org/pandas-docs/stable/user_guide/enhancingperf.html) libraries

Many of these might be somewhat generic rather than qhub specific, may be they would be more fitting for something like a full-featured recommended environment, as opposed to the rather bare default environments.
