### ISSUE TITLE
Dask workers should run with same permissions as the user that launches the dask gateway

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#62]
This issue addresses the comments and hiccups discussed [here](https://github.com/Quansight/quansight-internal-support/issues/53).

The need for this ticket is to keep track of the issue within the QHub repository.

**Comment by brl0** [comment]
I still think this issue should be addressed.

**Comment by viniciusdc** [comment]
@costrouc Have we already adressed this feature?

**Comment by brl0** [comment]
@viniciusdc,

This has not yet been addressed.  I just checked on qhub v0.3.12, and confirmed dask workers are running on root.

Here is a probably incomplete and only partially tested example of what I did to check:

<details>
<summary>whoami.py</summary>

```python
from dask_gateway import Gateway

gateway = Gateway()
options = gateway.cluster_options()
cluster = gateway.new_cluster(options)
client = cluster.get_client()
cluster.scale(1)

def whoami():
    import subprocess
    
    result = subprocess.run(["whoami"], capture_output=True, text=True)
    return result.stdout.strip()

results = client.run(whoami)
print(results)

client.close()
cluster.close()
del client
del cluster
```
</details>

It should also be noted that `/home/conda` is being mounted as `(rw)`, so while users' jupyterlab instances cannot modify conda-store environments because they are not running as root, dask workers can.  So in our case, when we need to install our internal package on workers, but because we want to ensure it is not installed into the conda-store environment, we have to take special care to install the package in user mode and the install location added to the python system path, which we accomplish with the following:

<details>
<summary>pip-user.py</summary>

```python
import os
import site
import sys

cmd = sys.executable + ' -m pip install -U --user "git+https://{token_string}github.com/{repo}.git{version_string}"'
os.system(cmd)
sys.path.append(site.USER_SITE)
```
</details>

So while I still think this issue should be fixed, now I am also curious if the mount of `/home/conda` should be changed to be read only?
