### ISSUE TITLE
QHub CDSDashboards are not sharable showing forbidden

### ISSUE THREAD

**Issue by costrouc** [Quansight/qhub#624]
## Describe the bug

When a user creates a dashboard and select "All users" for allowing anyone to view the dashboard once launched user's other than the user that launched the dashboard are forbidden getting a message "403: Forbidden"

Here are some example logs

```
notebook WARNING:tornado.application:Not allowing Hub user costrouchov@quansight.com                                                                                                                                               notebook WARNING:tornado.application:Detected unused OAuth state cookies                                                                                                                                                           notebook WARNING:tornado.general:403 GET /user/psimonard@quansight.com/dash-earthquakes/ (10.128.0.4): user costrouchov@quansight.com is not allowed.                                                                             
notebook WARNING:tornado.access:403 GET /user/psimonard@quansight.com/dash-earthquakes/ (10.128.0.4) 1.71ms      
```

This was tested on the `quansight.qhub.com` cluster.

**Comment by danlester** [comment]
For some reason the env vars JUPYTERHUB_ANYONE and JUPYTERHUB_GROUP are being dropped when the dashboard server spawns. Not sure why, will have to replicate the setup entirely I think to debug.

**Comment by danlester** [comment]
I believe this is to do with Kubespawner and/or JupyterHub versions getting out of sync.

In v0.3.11 they are specified as >= version numbers.

In main they are now pinned exactly, I think because of errors similar to the one we're seeing now: https://github.com/Quansight/qhub/blob/main/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/image/jupyterhub/environment.yaml

Having said that, I'm not yet convinced the version numbers in main at the moment are exactly the right combination for this to work! I'll have to experiment fully.
