### ISSUE TITLE
Failed deployment due to terraform modules version [bug]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#636]
I am currently trying to update to a more version of qhub to make use of the GPU fixes. I am encountering a terraform error that I do not know how to go about debugging. I wonder can someone help...

I am using the 0.3.11 docker images with qhub version b81810441010b2031ee52865cb1fd392a20dd7d8 and a branch of the terraform modules:

```
terraform_modules:
  repository: "github.com/quansight/qhub-terraform-modules"
  rev: "gke-internal-lb-with-dask-gateway"
```

The above branch has some deployment specific settings to use an internal load balancer. Previously I would rebase this branch for deployment updates that included changes to terraform modules. Any ideas what the best strategy for updates is now that the terraform modules are not stored in a separate repo?

<details>
<summary>Tail of error message during deployment </summary>
<br>

```
  [terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_config_map.gateway: Modifying... [id=qhub/qhub-daskgateway-gateway]
  [terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_config_map.gateway: Modifications complete after 0s [id=qhub/qhub-daskgateway-gateway]
  [terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_deployment.gateway: Modifying... [id=qhub/qhub-daskgateway-gateway]
  [terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Modifying... [id=jupyterhub]
  [terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_deployment.gateway: Modifications complete after 0s [id=qhub/qhub-daskgateway-gateway]
  [terraform]: module.forwardauth.kubernetes_manifest.forwardauth-middleware: Creating...
  [terraform]: module.qhub.kubernetes_manifest.forwardauth: Creating...
  [terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_manifest.cluster-middleware-stripprefix: Creating...
  [terraform]: module.qhub.kubernetes_manifest.forwardauth: Creation complete after 0s
  [terraform]: module.forwardauth.kubernetes_manifest.forwardauth-middleware: Creation complete after 1s
  [terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_manifest.cluster-middleware-stripprefix: Creation complete after 0s
  [terraform]: module.qhub.module.kubernetes-dask-gateway.kubernetes_manifest.cluster-middleware: Modifying...
  [terraform]: module.forwardauth.kubernetes_deployment.forwardauth-deployment: Creation complete after 3s [id=qhub/forwardauth-deployment]
  [terraform]: module.forwardauth.kubernetes_service.forwardauth-service: Creating...
  [terraform]: module.forwardauth.kubernetes_service.forwardauth-service: Creation complete after 0s [id=qhub/forwardauth-service]
  [terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Still modifying... [id=jupyterhub, 10s elapsed]
  [terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Still modifying... [id=jupyterhub, 20s elapsed]
  [terraform]: module.qhub.module.kubernetes-jupyterhub.helm_release.jupyterhub: Modifications complete after 29s [id=jupyterhub]
  [terraform]: 
  [terraform]: Error: API response status: Failure
  [terraform]: 
  [terraform]:   on modules/kubernetes/services/dask-gateway/middleware.tf line 24, in resource "kubernetes_manifest" "cluster-middleware":
  [terraform]:   24: resource "kubernetes_manifest" "cluster-middleware" {
  [terraform]: 
  [terraform]: Middleware.traefik.containo.us "qhub-dask-gateway-cluster" is invalid:
  [terraform]: spec.stripPrefixRegex: Invalid value: "null": spec.stripPrefixRegex in body
  [terraform]: must be of type object: "null"
  [terraform]: 
  [terraform]: 
  [terraform]: Error: Kubernetes API Error: Invalid Middleware.traefik.containo.us [qhub-dask-gateway-cluster]
  [terraform]: 
  [terraform]:   on modules/kubernetes/services/dask-gateway/middleware.tf line 24, in resource "kubernetes_manifest" "cluster-middleware":
  [terraform]:   24: resource "kubernetes_manifest" "cluster-middleware" {
  [terraform]: 
  [terraform]: 
  [terraform]: 
  [terraform]: Error: spec.stripPrefixRegex
  [terraform]: 
  [terraform]:   on modules/kubernetes/services/dask-gateway/middleware.tf line 24, in resource "kubernetes_manifest" "cluster-middleware":
  [terraform]:   24: resource "kubernetes_manifest" "cluster-middleware" {
  [terraform]: 
  [terraform]: Invalid value: "null": spec.stripPrefixRegex in body must be of type object:
  [terraform]: "null"
  [terraform]: 
  Problem encountered: Terraform error
  ERROR: Job failed: command terminated with exit code 1
```

</details>

EDIT: My diagnosis of what is wrong my be completely wrong. [The docs](https://docs.qhub.dev/en/stable/source/02_get_started/04_configuration.html#terraform-modules) still seem to indicate specifying an external repo is fine

**Comment by danlester** [comment]
John, the docs default to 'stable' meaning v0.3.11 at the moment, and for that version of QHub you can indeed specify external terraform_modules.

From 'main' at the moment (and the commit you are using) the modules are contained within the qhub code so you would not be able to pull in the external modules.

By the way, it might make sense to use the 'main' tagged images too, e.g. quansight/qhub-jupyterlab:main - or sha-xxxxxx to pin to a particular commit, but be aware that we don't run the docker build for every single commit, only ones where the docker files have changed, so you would have to find the most recent commit (before the commit you are using) that actually build and tagged those images.

Anyway, we need a way for you to specify these terraform_modules quirks in your qhub-config.yaml ideally - or at least have a way to still specify your own terrafom_modules repo as a fallback. Are you in a good position to summarize what you need to configure and make a new issue for that? Perhaps it's just the first two commits [here](https://github.com/Quansight/qhub-terraform-modules/commits/3bb964eb45940764df7e77a78b40a05dc9affee4).

In general, hopefully 'main' branch works, but it isn't guaranteed to be stable of course. My view is that it's good to get code into main earlier rather than later so that it gets tested in the weekly integration tests.

I think I can see what the immediate problem is from your logs above so I will fix, although main will still not incorporate your terraform_modules of course.

**Comment by danlester** [comment]
The terraform error should be fixed when my new PR is merged.

Thanks for opening the other issue about external terraform modules.

**Comment by leej3** [comment]
Thanks for fixing this one so quickly!
