### ISSUE TITLE
Upgrade terraform version to 1.0.0

### ISSUE THREAD

**Issue by tylerpotts** [Quansight/qhub#643]
Terraform is version 1.0.0! Upgrade qhub to depend on this version

**Comment by costrouc** [comment]
This should be a good beginner issue. I believe it would only involve changing: https://github.com/Quansight/qhub/blob/main/qhub/constants.py. Let's leave this one for someone new on the team.

**Comment by costrouc** [comment]
# Success Criteria
 - QHub now uses terraform 1.0 for all QHub runs.

**Comment by tarundmsharma** [comment]
@danlester @tylerpotts @costrouc  As discussed i have performed below test and analysis. Please correct me if i have gone wrong somewhere.

Test1:
I did the deployment using the terraform v0.14.9.
Did redeployment using  terraform v1.0.0 to check if the existing qhub deployment can be updated. test was passed and redeployment went fine.
Test2:
Did qhub deployment using terraform v0.14.9.
and qhub destroy using terraform v1.0.0
test went fine.
Test3:
did normal deployment using terraform v1.0.0 and deployment went fine.
I do not see any issue with upgrading the terraform version to v1.0.0 .

Above test run were conducted locally, AWS, and GCP.

![image](https://user-images.githubusercontent.com/85969694/125038577-318ca200-e0b3-11eb-92ac-c5742e7b2301.png)
![image](https://user-images.githubusercontent.com/85969694/125038582-34879280-e0b3-11eb-861c-5f0083e65145.png)
![image](https://user-images.githubusercontent.com/85969694/125038596-38b3b000-e0b3-11eb-9904-13ef6d68c57f.png)
![image](https://user-images.githubusercontent.com/85969694/125038611-3d786400-e0b3-11eb-9b94-00c4e0adaa8e.png)

I have even tried the Latest terraform version v1.0.1 for local, AWS and GCP deployments and everything went fine.
If agreed we can upgrade the terraform version to v1.0.1 instead of v1.0.0

![image](https://user-images.githubusercontent.com/85969694/125038689-541ebb00-e0b3-11eb-82f7-9b828a068a31.png)
![image](https://user-images.githubusercontent.com/85969694/125038699-57b24200-e0b3-11eb-80d5-97669c2a12ec.png)
![image](https://user-images.githubusercontent.com/85969694/125038710-5a149c00-e0b3-11eb-9c89-bd0816f56a64.png)
![image](https://user-images.githubusercontent.com/85969694/125038725-5f71e680-e0b3-11eb-9548-85d4aa3af179.png)
![image](https://user-images.githubusercontent.com/85969694/125038737-639e0400-e0b3-11eb-91da-fc361055622c.png)
![image](https://user-images.githubusercontent.com/85969694/125038762-6a2c7b80-e0b3-11eb-9a86-7f04483c91d4.png)


PS: I did even try to use TERRAFORM_VERSION >= "1.0.0"  to accommodate future version upgrade. But the "qhub/provider/terraform.py" code doesnot support ">" or in other words, it expects "="

![image](https://user-images.githubusercontent.com/85969694/125038785-731d4d00-e0b3-11eb-9cc5-4ccc7a3761ff.png)
![image](https://user-images.githubusercontent.com/85969694/125038802-787a9780-e0b3-11eb-9321-73af93b9e21e.png)

Thank you.

**Comment by danlester** [comment]
@tarundmsharma That's fantastic, thanks for running the tests.

I had thought @utabe said there was a problem upgrading like that, but maybe he just meant he hadn't been able to try it.

Agree 1.0.1 is fine, or if easier we can just accept Abraham's existing PR.

**Comment by danlester** [comment]
I have merged the PR upgrading to 1.0.0 anyway for now.
