### ISSUE TITLE
Automated commits overwriting the script section of .gitlab-ci.yaml[bug]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#656]
## Describe the bug

This may not be a bug but just user error. I am deploying using gitlab ci. If I want to change the qhub version for the deployment I modify the `script` section of .gitlab-ci.yml and set `pip install ...` to the version I want to deploy. Upon deployment, an automated commit is pushed back that overwrites my change. Should I just simply be putting such commands in the `before_script` section of the qhub-config.yaml?

**Comment by leej3** [comment]
I tried switching the qhub install to the before_script section. It stays there... but the qhub install in the script is still written to .gitlab-ci.yml without fail... which installs over whatever version I have specified. 

So currently I have to revert that part of the autocommit following every deployment.

**Comment by brl0** [comment]
I'll put in another shameless plug for idea proposed [here](https://github.com/Quansight/qhub/issues/113#issuecomment-859056138).

**Comment by leej3** [comment]
Thanks @brl0, that solves my conundrum. I'm happy to close this in favor of that. And typically moving commands to the `before_script` section is an adequate solution for autocommits batting ones changes in the `script` section.

**Comment by brl0** [comment]
> I'm happy to close this in favor of that

IMO, I think this is worth keeping open.

My suggestion is basically to support an arbitrary qhub install command which would make it easy to use a custom branch or fork.
That said, I think this request is also reasonable, since a custom install should probably be a fallback or an option of last resort for more advanced or sophisticated scenarios.
But I really think it would help scenarios like this, where a temporary solution is needed before a feature is fully integrated into qhub and a new release is made with that change, which reasonably can sometimes take weeks.

**Comment by kcpevey** [comment]
This is SO FRUSTRATING. Just wanted to throw my two cents in there LOL :)

**Comment by danlester** [comment]
There is a mechanism in place for the GitHub Actions versions of the workflow allowing you to use a specific branch of qhub for the qhub install.

This is designed for development (e.g. main branch), but you could just as easily use the 'release-x.x.x' branch.

To use it, set a QHUB_GH_BRANCH env var as [described here](https://docs.qhub.dev/en/stable/source/06_developers_contrib_guide/04_tests.html#using-a-development-branch).

This perpetuates the correct pip install version even through redeployment due to [this block of code](https://github.com/Quansight/qhub/blob/9ca0e98d61b08618ffbbbafcd5bb0eb811b618b4/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.github/workflows/qhub-ops.yaml#L42) in the GitHub workflow.

Something similar is missing from GitLab, although the [pip install command](https://github.com/Quansight/qhub/blob/9ca0e98d61b08618ffbbbafcd5bb0eb811b618b4/qhub/template/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/.gitlab-ci.yml#L18) is correct.

**Comment by leej3** [comment]
Excellent. Thank you. I’ll take a look.
