### ISSUE TITLE
.pem integration [enhancement]

### ISSUE THREAD

**Issue by leej3** [Quansight/qhub#658]
## Description

This is a client request. We would like to support the following usage:

```
import swat
import os

os.environ['CAS_CLIENT_SSL_CA_LIST'] = "/opt/sas/viya/config/etc/SASSecurityCertificateFramework/cacerts/trustedcerts.pem"

conn = swat.CAS('https://sas.url.com/SASDrive', 5570,'username','password')
```

For this to work we think that the cert has to be installed in the jupyterlab instance. Is this correct @costrouc?

**Comment by costrouc** [comment]
Was looking at the documentation of the class https://github.com/sassoftware/python-swat/blob/main/swat/cas/connection.py. Since we don't have a great way of hiding set environment variable secrets. I think you'll need to copy the file into the right shared from folder and then set the environment variable in your python notebook/terminal. 

Related issues:
 - https://github.com/Quansight/qhub/issues/37
 - https://github.com/Quansight/qhub/issues/13

@leej3 does the advice above give you a path forward for supporting this request?

**Comment by leej3** [comment]
Thanks for the help on this. Sorry for the delayed reply. I had patchy access to the VPN. What you suggested worked as far as I can tell. I do not have a username/password to confirm full authentication. It sounds like there is another problem on their side that is confounding any further debugging so I will mark this as resolved for now.
