### ISSUE TITLE
pre-commit hooks

### ISSUE THREAD

**Issue by brl0** [Quansight/qhub#660]
Based on something I noticed in the [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks/blob/master/.pre-commit-config.yaml) repo, I think it would be a good idea to add some pre-commit hooks, to both the qhub repo itself, but also the template.

A couple of hooks that I think would be of interest are [hadolint-docker](https://github.com/hadolint/hadolint), and a couple of yaml linters, `check-yaml` and [yamllint](https://github.com/adrienverge/yamllint.git).
There are also a couple of others included there for bash scripts and markdown.
Also, a quick google search finds some interesting ones for terraform files, such as these by [gruntwork](https://github.com/gruntwork-io/pre-commit).
For python, I personally like using the black and isort pre-commit hooks.

Some care will be needed in handling or excluding some of the jinja templates, since those will likely not pass normal linting.  However, having the rendered templates linted would be a good idea.  Creating a pytest that is parameterized for each provider, then renders and lints the rendered files, would be a great way to integrate this capability.

This might also be incorporated into the `qhub validate` command, by calling `pre-commit run --all-files` from there.

**Comment by tylerpotts** [comment]
@brl0 We are thinking that the core idea of this is implemented in https://github.com/Quansight/qhub/pull/576

The idea of linting terraform files is more complex since there are many ways they can render, and they live as cookiecutter templates in the qhub repo. On a side note we are leaning towards using Terraform CDK which would eliminate the need for terraform linting.

@brl0 Could you break this out into smaller actionable issues if there is an implementation you'd like in particular?

I'm going to close this for now because there's no specific action to take.
