### ISSUE TITLE
Make qhub-config.yaml contents available within Kubernetes [enhancement]

### ISSUE THREAD

**Issue by danlester** [Quansight/qhub#902]
## Description

Create a configmap in kubernetes containing the qhub-config.yaml

## Value/benefit

An extension I am writing needs to know all available jupyterlab profile names, i.e. within a pod. The qhub-config.yaml could be stored in a configmap and mounted on the pod.

I only really need profiles if we don't want everything in the yaml to be available - or we could mask certain secrets etc.

**Comment by Adam-D-Lewis** [comment]
I wonder if this could be beneficial to the backup/restore solution.  I like having this on k8s because it's sometimes possible for the deployed state to differ from what is in the qhub-config.yaml file (GitOps fails, if you aren't using GitOps, the state of the cluster while a redeploy is happening, etc.).  I hadn't thought about potential secrets in the qhub config file much, but assumed we could use a configmap to store the qhub-config file in.

**Comment by costrouc** [comment]
I'd prefer that this is a Kubernetes secret. Reason being is that the `qhub-config.yaml` could have some sensitive information inside of it. Otherwise however I love this idea :smile:

**Comment by danlester** [comment]
Yes, it should be a secret. I don't think that changes anything much.
