### ISSUE TITLE
[bug] End-to-end integration tests are failing

### ISSUE THREAD

**Issue by iameskild** [Quansight/qhub#928]
## Describe the bug

All of the cloud provider end-to-end tests are currently failing with following error message: 
```
[terraform]: │ Error: error initializing keycloak provider
[terraform]: │ 
[terraform]: │   with provider["registry.terraform.io/mrparkers/keycloak"],
[terraform]: │   on kubernetes.tf line 140, in provider "keycloak":
[terraform]: │  140: provider "keycloak" {
[terraform]: │ 
[terraform]: │ error sending POST request to
[terraform]: │ https://qhub-integration-test-aws.qhub.dev/auth/realms/master/protocol/openid-connect/token:
[terraform]: │ 401 Unauthorized
[terraform]: ╵
```

**Comment by viniciusdc** [comment]
As for local https://github.com/Quansight/qhub/issues/908, I got the same on a Linux deployment recently

**Comment by iameskild** [comment]
I've attempted deploying QHub on AWS using a similar setup to that of the [`qhub-integration-test-aws` ](https://github.com/Quansight/qhub-integration-test-aws):

Initialize `qhub-config.yaml`
```
export QHUB_GH_BRANCH=main

python -m qhub init aws \
--domain eaeaws.qhub.dev \
--project eaeaws \
--auth-provider password \
--repository github.com/iameskild/eaeaws \
--repository-auto-provision \
--ci-provider=none
```

Update default AWS region and deploy.

```
python -m qhub deploy -c qhub-config.yaml \
--dns-provider cloudflare \
--dns-auto-provision \
--disable-prompt         
```

And resulting deployment fails with the following error message:
```
[terraform]: │ Error: Kubernetes cluster unreachable: Get "https://D10AB8EE7842463A17356A352652EF2E.gr7.us-east-1.eks.amazonaws.com/version?timeout=32s": dial tcp: lookup D10AB8EE7842463A17356A352652EF2E.gr7.us-east-1.eks.amazonaws.com on 192.168.0.1:53: write udp 192.168.0.184:49396->192.168.0.1:53: write: network is down
[terraform]: │ 
[terraform]: │   with module.kubernetes-keycloak-helm.helm_release.keycloak,
[terraform]: │   on modules/kubernetes/keycloak-helm/main.tf line 1, in resource "helm_release" "keycloak":
[terraform]: │    1: resource "helm_release" "keycloak" {
[terraform]: │ 
[terraform]: ╵
[terraform]: Releasing state lock. This may take a few moments...

Problem encountered: Terraform error
```

More investigating is required.

**Comment by danlester** [comment]
I've been using Digital Ocean and Google Cloud this week without any problems.

But I have always used HTTPS with genuine Let's Encrypt certs.

While most of `qhub deploy` can work to a 'fake' domain, or one that isn't really accessible locally (maybe due to outdated DNS or cert problems), the Terraform Keycloak provider needs to communicate directly with the Keycloak API on a valid domain.

This is the kind of problem that will result in 'error initializing keycloak provider' (the first one eskild reported above). The code aims to tell it not to verify TLS if the qhub-config.yaml specifies a self-signed cert or if it is a 'local' deployment - but it's possible that's the bit that's broken as I've only done genuine Let's Encrypt deployments recently.

As for your more recent message (Kubernetes cluster unreachable) that doesn't look like a Keycloak problem as such - just a Helm one. But Keycloak is the first thing to be installed of course, so it's likely that JupyterHub (and maybe everything else) would also fail for the same reason.

**Comment by iameskild** [comment]
I tried redeploying on AWS with a signed SSL cert from Lets Encrypt and got the following error:
```
[terraform]: │ Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: RequestError: send request failed
[terraform]: │ caused by: Post "https://sts.amazonaws.com/": read tcp 192.168.0.184:57197->52.46.149.173:443: read: connection reset by peer
[terraform]: │ 
[terraform]: │   with provider["registry.terraform.io/hashicorp/aws"],
[terraform]: │   on aws.tf line 1, in provider "aws":
[terraform]: │    1: provider "aws" {
[terraform]: │ 
[terraform]: ╵
[terraform]: Releasing state lock. This may take a few moments...
```

I did successfully deploy to Digital Ocean when using a signed cert.

**Comment by iameskild** [comment]
Closed here https://github.com/Quansight/qhub-integration-test/pull/26
